### ISSUE TITLE
New route to return available desktop types

### ISSUE THREAD

**Issue by benarmston** [openflighthpc/flight-desktop-server#12]
Add a new route `GET /desktops` which uses `flight desktop avail` to determine the available desktop types and return a representation of them to the client.

---

Return a list of all available desktop types. The data attribute MAY be empty.

```
GET /desktops
Authorization: Basic <base64 encoded username:password>
Accepts: application/json

HTTP/2 200 OK
{
  "data": [
    <desktop-resource-object>,
    ...
  ]
}
```

A desktop-resource-object is defined as follows:

```
{
  "name":  "<the name reported by `flight desktop avail`>",
  "summary": "<the summary reported by `flight desktop avail`>",
  "state": "<the verification state as reported by `flight desktop avail`. Either Verified or Unverified>"
}
```

**Comment by WilliamMcCumstie** [comment]
This issue should have auto closed

**Comment by benarmston** [comment]
I don't think this is quite ready to be closed.  If I've read #20 correctly, the representation for a desktop doesn't include the summary field.

Currently, the client displays desktops like this:

![image](https://user-images.githubusercontent.com/287050/77742347-46ecd280-700e-11ea-8fdc-154d02a2da7f.png)

To do so, it hard-codes the summary of the desktop (here "GNOME v3, a free and open-source desktop environment...").  That string was lifted directly from the output of `flight desktop avail`.

The representation should include that so the hard-coding can be removed from the client.

**Comment by WilliamMcCumstie** [comment]
The desktop summary has been added
